
INSERT INTO `rlfdb`.`rlf_programs`
(`Program_Number`,`Program_Name`,`Equipment_List`,`Description`)
VALUES
(0,'Rest','NONE','Relax and Heal.'),
(1,'Back and Chest Boost','Weights or Bands\nPush-up bars\nPull-up bar or bands\nChair\nFitness guide and pen\nWater and Towel','Superset two of the body\'s largest muscle groups for a lactic acid bath like no other! You\'ll be fully pumped five minutes into the program, and your muscles will beg for mercy the rest of the way. Your body will learn how to keep it together under duress as you struggle to meet your target number of reps during round two. And if you feel a little queasy after your set, at least you\'ll know you\'re not alone.'),
(2,'Explosive Movement Boost','Heart rate monitor\nMat\nStool or Chair\nWater and towel','Plyometrics are drills designed to connect strength with speed to produce power. Also known as \"jump training\", this technique emerged in Eastern Europe in the early 1970s. Coined by American track coach Fred Will, the term derives from the Latin plyo+metrics, or \"measurable increases\". Plyometric training relates to any activity that requires speed and strength, as it improves your ability to run faster, jump higher, and maneuver in multidirectional sports. If your game involves a court, field, track, mat, pool, ring, rink, or mountain, Plyometrics can help.'),
(3,'Arms and Shoulders Boost','Weights or bands, Wall\nChair\nFitness guide and pen\nwater and towel','Applying the same principles as Chest & Back, you\'ll superset these muscle groups to exhaustion. As you\'ll be using smaller muscles, this might prove slightly less of a struggle - but that doesn\'t mean you won\'t be fully maxed when this workout is said and done. Just be sure to keep your form during the latter part of the routine, when you\'ll be tempted to cheat your range of motion. Maintaining good form is critical for proper muscular development and preventing injury, so stay strict and get ripped!'),
(4,'Yoga Flex','Mat\nYoga blocks\nWater and towel','Namaste... welcome to Yoga X. The philosophy of hatha yoga, on which this program is based, is that the more you can focus on the breath through each pose, the less you will notice the strain and discomfort. That\'s the goal of this workout. Although guys in particular may question yoga\'s place in the X program, after one session they will understand why this body-sculpting workout is a vital part of extreme fitness and an integral component of P90X. If you\'re new to yoga, this won\'t be easy - but you\'ll be amazed at your progress in just 90 days.'),
(5,'Back and Legs Boost','Weights or bands\nWall\nPull-up bar or bands\nChair\nFitness guide and pen\nWater and towel','The Top-to-Bottom Resistance Calorie Burner. This workout went through more stages in its development than a prepubescent. Originally it was just a leg workout, but the pilot and test groups felt that the program was too heavy on the legs and too light on, well, everything else. Tony can take a hint, and so was born this two-fisted, two-legged, total-body resistance blaster. While the main focus of the program lies in strengthening and developing the leg muscles (quads, glutes, hamstrings, and calves), there\'s also a handful of good old-fashioned pull-up exercises to give your legs a much deserved break while you work the upper body.'),
(6,'Martial Arts','Heart rate monitor\nWater and towel','Cardiovascular Self-Defense. Kenpo karate stated with native Hawaiian Ed Parker Sr., who studied under martial arts master William Chow and Lau Bon. Parker\'s journey exposed him to the spectrum of marital art forms that originated in China, India, and Asia, which he combined to create Kenpo, a raw street-fighting style and the first American system of martial arts. American Kenpo emphasizes the assets of gravity and economy of motion - everything is used, nothing wasted. In the end, one comes to know that the real weapon is not the fist or the foot, but the whole body. Kenpo X was designed to give P90X users a high-intensity cardiovascular workout loaded with fun, explosive combinations to improve balance, flexibility, coordination, stamina, and confidence.'),
(7,'Stretch Flex','Mat\nYoga blocks\nWater and towel','Flexibility - the Fountain of Youth. Flexibility training often takes a back seat to strength, speed, power, and cardiovascular endurance work, but the truth is that it can help you achieve a higher level of athleticism over a longer period of time. The reason why so many fit people are inflexible is because they rarely ever work at it! Ignoring this aspect of your training is a recipe for getting injured and hitting a plateau. It only stands to reason that the more you contract your muscles, the more you need to stretch them back out.'),
(8,'Essential Muscle Boost','Mat\nWeights or bands\nPlastic plate\ncardboard or towel\nWater and towel','Each and every exercise in the Core Synergistics workout recruits multiple muscle groups to build and support the core (lumbar spine and trunk muscles), while at the same time conditioning your body from head to toe. Loaded with a variety of fun, unique, and challenging exercises, this routine will get you moving in all directions to maximize your results.'),
(9,'Triceps, Shoulders and Chest Boost','Weights or Bands\nPush-up bars\nPlastic plate\ncardboard or towel\nChair\nFitness guide and pen\nWater and towel','Do this upper-body blast a few times, and we guarantee that you\'ll never have to worry about anyone kicking sand in your face at the beach again. Even if you\'re not looking to bust out of your T-shirt, this series of exercises will leave you feeling super-chiseled on top. Just be prepared to \"drop and give 20\" on more than one occasion. And ladies, if you keep your reps in the 12 to 15 range, you\'ll be sure to make the boys swoon. The good news: No curls or pull-ups today. The better news: There\'s every other move under the sun. So get ready to burn. Get ready to shred. If you really want to add some size, now is the time to go for it.  Use enough weight on each exercise so that you max out at 8 to 10 reps.  If you just want to continue developing lean muscle, use enough weight so that you max out between 12 and 15 reps.  Never do 11... (we kid you).  Also keep in mind that your body only builds muscle while at rest.  So try to get at least seven hours of sleep - which should be easy, because this schedule will wipe you out.'),
(10,'Biceps and Back Boost','Weights or bands\nWall\nPull-up bar or bands\nChair\nFitness guide and pen\nWater and towel','This program leads to some jaw-dropping biceps, also knows as \"guns\" in the weight training world. While guys will definitely add major size to their favorite mirror muscle, this workout wil also do wonders for women who just want to tighten and give definition to their back and upper arms. No matter what your goals for this routine, you will achieve them in dramatic fashion - just get ready to do a whole bunch of pulls and curls. When you\'re done, we guarantee you\'ll be your own \"gun show\".'),
(11,'Cardio Boost','Stool or Chair\nMat\nYoga blocks\nHeart rate monitor\nWater and towel','This low-impact cardio routine can be used in a variety of ways to meet your P90X goals. Use it in addition to your standard P90X workload when you want to burn some extra calories, or as a substitute if your body needs a break from the program\'s high-impact workouts. Whatever your reason for using Cardio X, you\'ll find it to be a fun, full-throttle, fat burning workout that will leave you feeling lean and mean.'),
(12,'Abdominal Boost','Mat\nWater and towel','In spite of what pop culture would have us believe, showing off your 6-pack is the least important reason for doing ab and core work. The muscles of your midsection are a crucial power source - it\'s where you transmit force between your upper and lower body, No athlete, regardless of the sport, can succeed without a solid core foundation. The resulting washboard is merely a bonus! The variety of movements in Ab Ripper X leaves no muscle unscathed. It\'s extreme work that\'s better than any machine in any club. Level 1: 15 to 20 reps Level 2: 20 to 25 reps')
