

INSERT INTO `rlfdb`.`RLF_Programs_Strategies`
(`Program_ID`,`Program_Strategy`,`Primary_Program_Name`,`Secondary_Program_Name`)
VALUES
(1,'Real Performance','Back and Chest Boost','Abdominal Boost'),
(2,'Real Performance','Explosive Movement Boost','Rest'),
(3,'Real Performance','Arms and Shoulders Boost','Abdominal Boost'),
(4,'Real Performance','Yoga Flex','Rest'),
(5,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(6,'Real Performance','Martial Arts','Rest'),
(7,'Real Performance','Rest','Stretch Flex'),
(8,'Real Performance','Back and Chest Boost','Abdominal Boost'),
(9,'Real Performance','Explosive Movement Boost','Rest'),
(10,'Real Performance','Arms and Shoulders Boost','Abdominal Boost'),
(11,'Real Performance','Yoga Flex','Rest'),
(12,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(13,'Real Performance','Martial Arts','Rest'),
(14,'Real Performance','Rest','Stretch Flex'),
(15,'Real Performance','Back and Chest Boost','Abdominal Boost'),
(16,'Real Performance','Explosive Movement Boost','Rest'),
(17,'Real Performance','Arms and Shoulders Boost','Abdominal Boost'),
(18,'Real Performance','Yoga Flex','Rest'),
(19,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(20,'Real Performance','Martial Arts','Rest'),
(21,'Real Performance','Rest','Stretch Flex'),
(22,'Real Performance','Yoga Flex','Rest'),
(23,'Real Performance','Essential Muscle Boost','Rest'),
(24,'Real Performance','Martial Arts','Rest'),
(25,'Real Performance','Stretch Flex','Rest'),
(26,'Real Performance','Essential Muscle Boost','Rest'),
(27,'Real Performance','Yoga Flex','Rest'),
(28,'Real Performance','Rest','Stretch Flex'),
(29,'Real Performance','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(30,'Real Performance','Explosive Movement Boost','Rest'),
(31,'Real Performance','Biceps and Back Boost','Abdominal Boost'),
(32,'Real Performance','Yoga Flex','Rest'),
(33,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(34,'Real Performance','Martial Arts','Rest'),
(35,'Real Performance','Rest','Stretch Flex'),
(36,'Real Performance','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(37,'Real Performance','Explosive Movement Boost','Rest'),
(38,'Real Performance','Biceps and Back Boost','Abdominal Boost'),
(39,'Real Performance','Yoga Flex','Rest'),
(40,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(41,'Real Performance','Martial Arts','Rest'),
(42,'Real Performance','Rest','Stretch Flex'),
(43,'Real Performance','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(44,'Real Performance','Explosive Movement Boost','Rest'),
(45,'Real Performance','Biceps and Back Boost','Abdominal Boost'),
(46,'Real Performance','Yoga Flex','Rest'),
(47,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(48,'Real Performance','Martial Arts','Rest'),
(49,'Real Performance','Rest','Stretch Flex'),
(50,'Real Performance','Yoga Flex','Rest'),
(51,'Real Performance','Essential Muscle Boost','Rest'),
(52,'Real Performance','Martial Arts','Rest'),
(53,'Real Performance','Stretch Flex','Rest'),
(54,'Real Performance','Essential Muscle Boost','Rest'),
(55,'Real Performance','Yoga Flex','Rest'),
(56,'Real Performance','Rest','Stretch Flex'),
(57,'Real Performance','Back and Chest Boost','Abdominal Boost'),
(58,'Real Performance','Explosive Movement Boost','Rest'),
(59,'Real Performance','Arms and Shoulders Boost','Abdominal Boost'),
(60,'Real Performance','Yoga Flex','Rest'),
(61,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(62,'Real Performance','Martial Arts','Rest'),
(63,'Real Performance','Rest','Stretch Flex'),
(64,'Real Performance','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(65,'Real Performance','Explosive Movement Boost','Rest'),
(66,'Real Performance','Biceps and Back Boost','Abdominal Boost'),
(67,'Real Performance','Yoga Flex','Rest'),
(68,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(69,'Real Performance','Martial Arts','Rest'),
(70,'Real Performance','Rest','Stretch Flex'),
(71,'Real Performance','Back and Chest Boost','Abdominal Boost'),
(72,'Real Performance','Explosive Movement Boost','Rest'),
(73,'Real Performance','Arms and Shoulders Boost','Abdominal Boost'),
(74,'Real Performance','Yoga Flex','Rest'),
(75,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(76,'Real Performance','Martial Arts','Rest'),
(77,'Real Performance','Rest','Stretch Flex'),
(78,'Real Performance','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(79,'Real Performance','Explosive Movement Boost','Rest'),
(80,'Real Performance','Biceps and Back Boost','Abdominal Boost'),
(81,'Real Performance','Yoga Flex','Rest'),
(82,'Real Performance','Back and Legs Boost','Abdominal Boost'),
(83,'Real Performance','Martial Arts','Rest'),
(84,'Real Performance','Rest','Stretch Flex'),
(85,'Real Performance','Yoga Flex','Rest'),
(86,'Real Performance','Essential Muscle Boost','Rest'),
(87,'Real Performance','Martial Arts','Rest'),
(88,'Real Performance','Stretch Flex','Rest'),
(89,'Real Performance','Essential Muscle Boost','Rest'),
(90,'Real Performance','Yoga Flex','Rest'),
(91,'Real Performance','Rest','Stretch Flex'),
(92,'Real Lean','Essential Muscle Boost','Rest'),
(93,'Real Lean','Cardio Boost','Rest'),
(94,'Real Lean','Arms and Shoulders Boost','Abdominal Boost'),
(95,'Real Lean','Yoga Flex','Rest'),
(96,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(97,'Real Lean','Martial Arts','Rest'),
(98,'Real Lean','Rest','Stretch Flex'),
(99,'Real Lean','Essential Muscle Boost','Rest'),
(100,'Real Lean','Cardio Boost','Rest'),
(101,'Real Lean','Arms and Shoulders Boost','Abdominal Boost'),
(102,'Real Lean','Yoga Flex','Rest'),
(103,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(104,'Real Lean','Martial Arts','Rest'),
(105,'Real Lean','Rest','Stretch Flex'),
(106,'Real Lean','Essential Muscle Boost','Rest'),
(107,'Real Lean','Cardio Boost','Rest'),
(108,'Real Lean','Arms and Shoulders Boost','Abdominal Boost'),
(109,'Real Lean','Yoga Flex','Rest'),
(110,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(111,'Real Lean','Martial Arts','Rest'),
(112,'Real Lean','Rest','Stretch Flex'),
(113,'Real Lean','Yoga Flex','Rest'),
(114,'Real Lean','Essential Muscle Boost','Rest'),
(115,'Real Lean','Martial Arts','Rest'),
(116,'Real Lean','Stretch Flex','Rest'),
(117,'Real Lean','Cardio Boost','Rest'),
(118,'Real Lean','Yoga Flex','Rest'),
(119,'Real Lean','Rest','Stretch Flex'),
(120,'Real Lean','Essential Muscle Boost','Rest'),
(121,'Real Lean','Cardio Boost','Rest'),
(122,'Real Lean','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(123,'Real Lean','Yoga Flex','Rest'),
(124,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(125,'Real Lean','Martial Arts','Rest'),
(126,'Real Lean','Rest','Stretch Flex'),
(127,'Real Lean','Essential Muscle Boost','Rest'),
(128,'Real Lean','Cardio Boost','Rest'),
(129,'Real Lean','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(130,'Real Lean','Yoga Flex','Rest'),
(131,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(132,'Real Lean','Martial Arts','Rest'),
(133,'Real Lean','Rest','Stretch Flex'),
(134,'Real Lean','Essential Muscle Boost','Rest'),
(135,'Real Lean','Cardio Boost','Rest'),
(136,'Real Lean','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(137,'Real Lean','Yoga Flex','Rest'),
(138,'Real Lean','Back and Legs Boost','Abdominal Boost'),
(139,'Real Lean','Martial Arts','Rest'),
(140,'Real Lean','Rest','Stretch Flex'),
(141,'Real Lean','Yoga Flex','Rest'),
(142,'Real Lean','Essential Muscle Boost','Rest'),
(143,'Real Lean','Martial Arts','Rest'),
(144,'Real Lean','Stretch Flex','Rest'),
(145,'Real Lean','Cardio Boost','Rest'),
(146,'Real Lean','Yoga Flex','Rest'),
(147,'Real Lean','Rest','Stretch Flex'),
(148,'Real Lean','Back and Chest Boost','Abdominal Boost'),
(149,'Real Lean','Cardio Boost','Rest'),
(150,'Real Lean','Arms and Shoulders Boost','Abdominal Boost'),
(151,'Real Lean','Yoga Flex','Rest'),
(152,'Real Lean','Essential Muscle Boost','Rest'),
(153,'Real Lean','Martial Arts','Rest'),
(154,'Real Lean','Rest','Stretch Flex'),
(155,'Real Lean','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(156,'Real Lean','Cardio Boost','Rest'),
(157,'Real Lean','Biceps and Back Boost','Abdominal Boost'),
(158,'Real Lean','Yoga Flex','Rest'),
(159,'Real Lean','Essential Muscle Boost','Rest'),
(160,'Real Lean','Martial Arts','Rest'),
(161,'Real Lean','Rest','Stretch Flex'),
(162,'Real Lean','Back and Chest Boost','Abdominal Boost'),
(163,'Real Lean','Cardio Boost','Rest'),
(164,'Real Lean','Arms and Shoulders Boost','Abdominal Boost'),
(165,'Real Lean','Yoga Flex','Rest'),
(166,'Real Lean','Essential Muscle Boost','Rest'),
(167,'Real Lean','Martial Arts','Rest'),
(168,'Real Lean','Rest','Stretch Flex'),
(169,'Real Lean','Triceps, Shoulders and Chest Boost','Abdominal Boost'),
(170,'Real Lean','Cardio Boost','Rest'),
(171,'Real Lean','Biceps and Back Boost','Abdominal Boost'),
(172,'Real Lean','Yoga Flex','Rest'),
(173,'Real Lean','Essential Muscle Boost','Rest'),
(174,'Real Lean','Martial Arts','Rest'),
(175,'Real Lean','Rest','Stretch Flex'),
(176,'Real Lean','Yoga Flex','Rest'),
(177,'Real Lean','Essential Muscle Boost','Rest'),
(178,'Real Lean','Martial Arts','Rest'),
(179,'Real Lean','Stretch Flex','Rest'),
(180,'Real Lean','Cardio Boost','Rest'),
(181,'Real Lean','Yoga Flex','Rest'),
(182,'Real Lean','Rest','Stretch Flex')
